---
debug: true
contextTimeout: 5

server:
  port: '8080'
  host: '127.0.0.1'
  env: 'local'
  useRedis: false

services:

database:
  driver: 'postgres'
  host: 'localhost'
  port: 5432
  username: 'erp-dev'
  password: 'erp-dev'
  name: 'erp-dev'
  sslmode: 'disable'
  maxOpenConnections: 10
  maxIdleConnections: 5
  maxConnectionLifetime: 300
  timezone: 'Asia/Ho_Chi_Minh'

jwt:
  secret: 'hgG6T23XD25N'
  accessTokenExpiresIn: 3600
  refreshTokenExpiresIn: 86400
